version: '3.8'
services:
  db:
    image: postgres:15 # Using PostgreSQL version 15
    restart: always
    environment:
      POSTGRES_USER: postgres # Default user
      POSTGRES_PASSWORD: GgvpIzikatka228! # User-provided password
      POSTGRES_DB: mosh # Database name
    ports:
      - "5432:5432" # Map local port 5432 to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data

volumes:
  postgres_data:
